### ISSUE TITLE
Last character dropped on cmdMessenger.sendCmd

### ISSUE THREAD

**Issue by Pablo1** [dreamcat4/CmdMessenger2#1]
Sometimes the last character is dropped (as seen in the serial monitor) when sending commands from the arduino. This doesn't happen in acknowledgement in the callback but does happen most of the time when it's in a method called by the callback.

**Comment by dreamcat4** [comment]
If possible, can you please upload a gist of the console output, along with any modifications in your program?

**Comment by Pablo1** [comment]
Sorry for the trouble. Turned out to be an error on my part in not account for the null character in the string length.
